resources:
  - url: /local/mini-media-player-bundle.js?v=1.11.0
    type: module

title: Home Assistant
views:
  - title: Home
    icon: mdi:home
    cards:
      - !include light_cards.yaml
      - !include media_player_cards.yaml
  - title: Lights
    icon: mdi:lightbulb
    cards:
      - !include light_cards.yaml
  - title: Media Player
    icon: mdi:music-note
    cards:
      - !include media_player_cards.yaml
  - title: Alarm Clock
    icon: mdi:alarm
    cards:
      - !include alarm_clock_cards.yaml

