resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.5
    type: module
  - url: /local/vertical-stack-in-card.js?v=0.0.8
    type: js

title: Home Assistant
views:
- title: Home
  icon: mdi:home
  cards:
    - !include light_cards.yaml
    - !include media_player_cards.yaml
- title: Lights
  icon: mdi:lightbulb
  cards:
    - !include light_cards.yaml
- title: Media Player
  icon: mdi:music-note
  cards:
    - !include media_player_cards.yaml

