resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.5
    type: module
  - url: /local/vertical-stack-in-card.js?v=0.0.8
    type: js

title: Home Assistant @ hippo
views:
- type: horizontal-stack
  cards:
    - type: entities
      # title: Lights
      # show_header_toggle: false
      entities:
        - entity: light.living_room
          name: Lights
          icon: none
        - entity: input_number.light_color_temperature
          name:  Color Temperature
          icon: mdi:thermometer
        - entity: input_boolean.auto_temperature_control
          name: Automatic Color Temperature Control
          icon: mdi:clock
    - type: horizontal-stack
      cards:
        - type: light
          entity: light.living_room
          name: Kitchen
        - type: light
          entity: light.living_room
          name: Living Room
    - type: custom:vertical-stack-in-card
      cards:
        - type: entities
          entities:
            - entity: input_boolean.media_player_on
              name: Media Player
              icon: none
        - type: conditional
          conditions:
            - entity: media_player.mopidy
              state_not: "off"
          card:
            type: entities
            entities:
              - entity: input_select.audio_input
                name: Mode
                icon: mdi:speaker
              - type: "custom:mini-media-player"
                entity: media_player.mopidy
                name: Volume
                group: true
                more_info: false
                hide_power: true 
                hide_controls: true
                hide_media_info: true
                hide_info: true
        - type: conditional  
          conditions:
            - entity: media_player.mopidy 
              state: "playing"
          card:
            type: "custom:mini-media-player"
            entity: media_player.mopidy
            name: Radio
            icon: mdi:radio
            show_source: small
            hide_power: true
            hide_controls: true
            hide_volume: true
            scroll_info: true
        - type: conditional
          conditions:
            - entity: media_player.mopidy
              state: "paused"
          card:
            type: "custom:mini-media-player"
            entity: media_player.spotify
            name: Spotify
            artwork: cover
            hide_volume: true
            hide_power: true
            show_progress: true
